/**:
  ros__parameters:
    num_timestamp: 11 # the number of past frames
    timestamp_threshold: 10000000000000.0 # [us]
    score_threshold: 0.0 # threshold of predicted score
    labels: ["VEHICLE"] # only ego vehicle is considered
    ego_dimensions: [4.0,2.0,1.7] # [length, width, height]
    propagate_future_states: true
    add_left_bias_history: false
    add_right_bias_history: false
    publish_debug_polyline_batch: false
    publish_debug_polyline_map: false
    future_state_propagation_sec: 3.0

    # labels: ["VEHICLE", "PEDESTRIAN", "MOTORCYCLIST", "CYCLIST", "BUS"]
    checkpoint_path: "$(var data_path)/mtr_best.pth"
    model_config: "$(find-pkg-share autoware_mtr_python)/config/mtr.yaml"
    lanelet_file: "$(find-pkg-share autoware_mtr_python)/config/odaiba.lanelet2_map.osm"
    intention_point_file: "$(find-pkg-share autoware_mtr_python)/data/cluster64_dict.pkl"

